### ISSUE TITLE
Address CVSS v3 and CVE json changes

### ISSUE THREAD

**Issue by hillaryj** [cisagov/cyhy-system#10]
There are some upcoming changes to the JSON files we use with CyHy.

This is a placeholder - @climber-girl will fill out more info by editing this issue in January.

**Comment by climber-girl** [comment]
Hi all, the ask here is to move toward reporting the base score of the latest CVSS version in the CyHy reports.  I envision this being a two step process (possibly three if we want to use SSVC instead of CVSS) so there is a transition period for folks to get used to us using the latest CVSS version available for each vulnerability.  I'd like to fully switch to the latest severity ratings by Oct. 1,  2021 (the start of FY22) with a transition to it starting NLT July 1, 2021.  If this isn't possible, I understand - just have to update the severity_starting_XXXX key noted in bullet 1 below.

Here are the steps I believe this change/transition will require:

1. Change the code pertaining to the CVE Collection in Mongo to gather all CVSS version base scores, and generate a new severity rating based on the latest. For example, instead of `{
    "_id" : "CVE-1999-0001",
    "cvss_score" : 5.0,
    "severity" : 2
}` report `{
    "_id" : "CVE-1999-0001",
    "cvss_v2_score" : 5.0,
    "cvss_v3_score" : null,
    "cvss_v3.1_score" : null,
    "current_severity" : 2,
    "severity_starting_oct01_2021" : 2,
}`.  Instead of `{
    "_id" : "CVE-2019-9544",
    "cvss_score" : 6.8,
    "severity" : 2
}` report `{
    "_id" : "CVE-2019-9544",
    "cvss_v2_score" : 6.8,
    "cvss_v3_score" : 8.8,
    "cvss_v3.1_score" : null,
    "current_severity" : 2,
    "severity_starting_oct01_2021" : 3
}`.
2. In the report's findings.csv, show CVSSv2 scores (where CVE is found - reminder: CVE-less vulns use Nessus scoring) with updated column header of "current_base_score" (updating "severity" to be "current_severity") and add three new columns denoting the "cvss_base_score_starting_oct01_2021," "cvss_version_reported_starting_oct01_2021," and "severity_starting_oct01_2021."  We will need to add a blurb to the "Vulnerability Scoring" section of the PDF under "4.2 Process" to document the transition and scoring changes to be seen.
3. The following attachments remain using the CVSSv2/Nessus severity until the change to use the latest is fully transitioned as will the PDF's Report Card, tables, and charts.  
   - days-currently-active.csv
   - days-to-mitigate.csv
   - false-postitive-findings.csv
   - recently-detected.csv
4. Items to discuss: 
   - The severity listed in mitigated-vulnerabilities.csv... I'm not sure whether we want to handle it like those attachments listed in bullet 3 or not.
   - Figure 10 in particular will either need to have it's label updated to "CVSS_v2_ Histogram for Active Vulnerabilities" until we transition (then idk) or just removed entirely (my vote for this option).  
   - Table 6 will need to be handled similarly, likely removed entirely for something with more useful info like Tenable VPR score or SSVC score.
   - Risk Rating System (tables 7 and 8)...  to remove or update with Tenable VPR/SSVC?
   - Appendix C will either need to have its CVSS column updated to "CVSSv2" until we transition and then updated to use the latest CVSS version base score and severity as well as add a column denoting which CVSS version is reported.

Once the transition period showing parallel scores is completed (desired date: 10/01/21), these are the steps I believe will need to be taken:

1. Update the report's findings.csv to remove the "current_base_score" and "current_severity" columns as well as rename:
   - "cvss_base_score_starting_oct01_2021" to "cvss_base_score"
   - "severity_starting_oct01_2021" to "severity"
   - "severity_starting_oct01_2021" to "severity"  
   - We will need to revise the blurb for the "Vulnerability Scoring" section of the PDF under "4.2 Process" to describe the new severity reporting process.
2. The following attachments "severity" column and the PDF Report Card, charts, and Tables will need to be updated to use the latest CVSS version.  
   - days-currently-active.csv
   - days-to-mitigate.csv
   - false-postitive-findings.csv
   - recently-detected.csv
3. Update the definitions of "severity" and "CVSS" under Appendix H (Glossary).

I probably missed something, so let me know what you think so far.  I can update where needed :)

**Comment by dav3r** [comment]
This work has been completed - see https://github.com/orgs/cisagov/projects/24 for details.
