### ISSUE TITLE
Add REV flag to KEV DB collection

### ISSUE THREAD

**Issue by KeithBonesJr** [cisagov/cyhy-system#100]
# 💡 Summary #

Add REV=true/false to the kev collection of the CyHy Database based on knownRansomwareCampaignUse="Known"/"Unknown in the KEV catalog

## Motivation and context ##

In support of Ransomware Vulnerability Warning Pilot, the stakeholders REV values need to be tracked in the KEV collection for pulling of various metrics to incorporate into specific CSV files and metrics gathering.

## Implementation notes ##

On https://www.cisa.gov/known-exploited-vulnerabilities-catalog the values should map as follows for the "Known To Be Used in Vulnerability Campaigns" column:

-Known maps to True for the REV key value in database
-Unknown maps to False for the REV key value in database

## Acceptance criteria ##

- [x] New key value named REV in the KEV collection of CyHy Database with values of True/False (Known/Unknown)

**Comment by dav3r** [comment]
@KeithBonesJr - You have listed two identical Acceptance Criteria items.  Did you mean to have two different items there or is the second one unintentional and should be deleted?

**Comment by KeithBonesJr** [comment]
@dav3r  just the single Acceptance Criteria

**Comment by jeffkause** [comment]
We are thinking in the lines of:

Under cyhy/db/database.py
   Under KEVDoc class definition,
   Add REV to document structure
   structure = {“_id”: basestring, “REV”: bool}

Should not be required, can be defaulted to None/null

 

Under bin/cyhy-kevsync,
  Line 51, gather knownRansomwareCampaignUse along with CVE data
  Line 54, Convert knownRansomwareCampaignUse into boolean type

Store true if “Known”, false if “Unknown”, null if neither, ignoring case

Text
rev = i.get(“knownRansomwareCampaignUse”).lower()

if rev == “known”:
	rev = True

elif rev == “unknown”:
	rev = False

else:
	rev = None
Expand (7 lines)

 

line 61
   Write to database based on knownRansomwareCampaignUse value from KEV JSON data
    entry_doc = db.KEVDoc({“_id”: cve, “REV”: rev})

**Comment by KeithBonesJr** [comment]
@jeffkause which repository should this be under?

**Comment by KeithBonesJr** [comment]
@dav3r  does it make more sense to create a PR draft instead or is this fine? We plan to bring this up during the 1 o'clock.

**Comment by jeffkause** [comment]
cyhy-core

**Comment by dav3r** [comment]
I will take care of the code changes for this issue since I will be in the best position to easily test them.  I added myself as the assignee for this issue.

**Comment by KeithBonesJr** [comment]
Thanks! @dav3r

**Comment by dav3r** [comment]
Is there a particular reason you want to leave the `rev` field null if `knownRansomwareCampaignUse` is not "Known" or "Unknown"?  Wouldn't it make more sense to simply set it to `True` if "Known" and `False` if anything else?

Also, I'm planning to name the database field `known_ransomware`, rather than `rev` since it's more explanatory.

**Comment by KeithBonesJr** [comment]
@dav3r  we were thinking of it from an input validation standpoint. If a `knownRansomwareCampaignUse` value is fat fingered, a misspelled "Known" value could be flagged as "Unknown". I believe the issue here is we don't know what type of input validation is happening on the KEV side for those values reported on the webpage.

We are fine with the database field rename, I agree yours is more explanatory.

**Comment by dav3r** [comment]
I don't think we as consumers of the KEV JSON feed are in a good position to make those sorts of determinations.  We are trusting the KEV/REV data source to be correct, otherwise we wouldn't be using it.  If there is a mistake, it is up to the provider of the data feed to correct it.  Once it's fixed, we will ingest the corrected data the next time we run our script.

In this particular case, anything other than "Known" would imply that the ransomware status is unknown, hence my suggestion.  Also, it's cleaner from a dev/DB standpoint if we can safely assume that we will always be populating the `known_ransomware` field with either `True` or `False`.

**Comment by KeithBonesJr** [comment]
@dav3r  sounds good, we are good with your recommendation.

**Comment by dav3r** [comment]
@KeithBonesJr and @jeffkause - https://github.com/cisagov/cyhy-core/pull/80 has been created to address this issue.  Feel free to take a look and comment on it if anything looks different than what you expected.

Once that PR is reviewed, approved, and merged, am I clear to deploy it to Production?  It should not affect anything else, so we are able to deploy it at our convenience.

**Comment by KeithBonesJr** [comment]
@dav3r looks good to us! Sure it can be deployed to production or held off until the other changes are made. It makes no difference to us.
